### ISSUE TITLE
algorithm doesn't compute the color index accurately anymore. Click for details

### ISSUE THREAD

**Issue by jdstep** [impromptu-sunset/impromptu-sunset#81]
the color index will keep going up for 1-2 seconds after the user has stopped typing, then fall rapidly. The previous way of calculating the algorithm worked really well, if there is a way we can revert to that

**Comment by plespe** [comment]
I'll take a look, I think it's a combination of the grace period + making the color green for the top three scores.

**Comment by jdstep** [comment]
It is possible to get it to be green, that part works fine. But I don't think it's related to the color being green for 8-10. To recreate it, let the color dip to red for a few second. Then type 3-4 characters and stop. The color index fluctuates rapidly without approaching green.
